# Generated by Django 4.0.1 on 2022-01-05 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id_clientes', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('doc', models.IntegerField()),
                ('about', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=10)),
                ('site', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresas', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('doc', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=10)),
                ('site', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lances',
            fields=[
                ('id_offer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ofertas',
            fields=[
                ('id_ofertas', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('de', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('initial_value', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('amount_type', models.CharField(max_length=10)),
            ],
        ),
    ]
