# Generated by Django 4.0 on 2022-01-09 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresas', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('doc', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=10)),
                ('site', models.CharField(max_length=255)),
            ],
        ),
    ]
